// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70uOlfF8qiYa1RzyKvxOyN42HVBB-iwQ',
    appId: '1:112985400778:web:2fe3d88a0aba7a9ee8db33',
    messagingSenderId: '112985400778',
    projectId: 'project-digitown',
    authDomain: 'project-digitown.firebaseapp.com',
    storageBucket: 'project-digitown.firebasestorage.app',
    measurementId: 'G-FC48WMMT79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbzRXgj1ITLKK7-Q4qKnVFo5ihtLrlPM',
    appId: '1:112985400778:android:86ac80b772f97020e8db33',
    messagingSenderId: '112985400778',
    projectId: 'project-digitown',
    storageBucket: 'project-digitown.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA70uOlfF8qiYa1RzyKvxOyN42HVBB-iwQ',
    appId: '1:112985400778:web:2fe3d88a0aba7a9ee8db33',
    messagingSenderId: '112985400778',
    projectId: 'project-digitown',
    authDomain: 'project-digitown.firebaseapp.com',
    storageBucket: 'project-digitown.firebasestorage.app',
    measurementId: 'G-FC48WMMT79',
  );
}
