// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlbJccw6r2OXDDlg6YiLkkm0Ti1mz1yB8',
    appId: '1:112985400778:web:ed47ff0058b287e2e8db33',
    messagingSenderId: '112985400778',
    projectId: 'project-digitown',
    authDomain: 'project-digitown.firebaseapp.com',
    databaseURL: 'https://project-digitown-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-digitown.firebasestorage.app',
    measurementId: 'G-KDW0ZN12FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbzRXgj1ITLKK7-Q4qKnVFo5ihtLrlPM',
    appId: '1:112985400778:android:cb81214b1187e4bfe8db33',
    messagingSenderId: '112985400778',
    projectId: 'project-digitown',
    storageBucket: 'project-digitown.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlbJccw6r2OXDDlg6YiLkkm0Ti1mz1yB8',
    appId: '1:112985400778:web:ff13c5d90d5b71b7e8db33',
    messagingSenderId: '112985400778',
    projectId: 'project-digitown',
    authDomain: 'project-digitown.firebaseapp.com',
    databaseURL: 'https://project-digitown-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-digitown.firebasestorage.app',
    measurementId: 'G-5HEMB5PXWM',
  );

}